name: ppfo_math_app
description: "PPFO v25.0 - نظام رياضي متكامل - د. سعودي محمد"
publish_to: 'none'
version: 25.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
